# Generated by Django 5.2.7 on 2025-10-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productivityentry',
            name='bundle_opening',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productivityentry',
            name='loading',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productivityentry',
            name='picking',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productivityentry',
            name='put_away',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productivityentry',
            name='scanning',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productivityentry',
            name='sorting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productivityentry',
            name='sticker',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
