# Generated by Django 5.2.7 on 2025-10-29 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0002_productivityentry_bundle_opening_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivityentry',
            name='lead',
            field=models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
